// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9G-FQeCz9YtSPFAIPxUW5ZOW_gxxXfsQ',
    appId: '1:886900694249:web:adc5c769aeb8e5b38de478',
    messagingSenderId: '886900694249',
    projectId: 'eduplas-1f09e',
    authDomain: 'eduplas-1f09e.firebaseapp.com',
    storageBucket: 'eduplas-1f09e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYO5F_DfOUQS4ijDwje8qTrFaUxMVrKCk',
    appId: '1:886900694249:android:7721eac11a1fe06c8de478',
    messagingSenderId: '886900694249',
    projectId: 'eduplas-1f09e',
    storageBucket: 'eduplas-1f09e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4fUxu7jCy0fBxwuCJ3BUJS-5GFxwbhw',
    appId: '1:886900694249:ios:209386dc456a1dab8de478',
    messagingSenderId: '886900694249',
    projectId: 'eduplas-1f09e',
    storageBucket: 'eduplas-1f09e.firebasestorage.app',
    iosBundleId: 'com.example.eduplas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4fUxu7jCy0fBxwuCJ3BUJS-5GFxwbhw',
    appId: '1:886900694249:ios:209386dc456a1dab8de478',
    messagingSenderId: '886900694249',
    projectId: 'eduplas-1f09e',
    storageBucket: 'eduplas-1f09e.firebasestorage.app',
    iosBundleId: 'com.example.eduplas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9G-FQeCz9YtSPFAIPxUW5ZOW_gxxXfsQ',
    appId: '1:886900694249:web:21af1ecd7c3ef6118de478',
    messagingSenderId: '886900694249',
    projectId: 'eduplas-1f09e',
    authDomain: 'eduplas-1f09e.firebaseapp.com',
    storageBucket: 'eduplas-1f09e.firebasestorage.app',
  );

}

